# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d74010b5ac7e71da1b22b058700f6f0bde81c5a1cadcd85c6ab484eb2bfae0a99867253e0c9287225b2e8b8c6ad18297c74d8a125d5eee32beda4996d4311af

test:
  secret_key_base: 1cba77506572a8849212fdd0166505f9188f73eac39785ba2d647776b1ed68ebc7d73fd7eb5f72e2a823e0f826c767cb1b8a70b0cca099c6be02c84aa82907a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
